name: bl_demolition_materials
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/project-kiertotalous/bl-demolition-materials

environment:
  sdk: ^3.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  equatable: ^2.0.0