name: bl_demolition_materials
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/project-kiertotalous/bl-demolition-materials

environment:
  sdk: ^3.6.1

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0

dependencies:
  equatable: ^2.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.2
